apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-with-karpenter-1
  region: eu-west-1
  version: '1.28'
  tags:
    karpenter.sh/discovery: cluster-with-karpenter-1 # here, it is set to the cluster name
iam:
  withOIDC: true # required

karpenter:
  version: 'v0.33.1' # Exact version must be specified

managedNodeGroups:
  - name: managed-ng-1
    minSize: 2
    maxSize: 2
    desiredCapacity: 2

